name: release-buildx

on:
  push:
    tags:
      - '*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,amd64
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Set Release Tag Env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Debug tags
        run: echo "${{ vars.REPOSITORY_OWNER }}"
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            benhunter:latest
            ${{ vars.REPOSITORY_OWNER }}:${{ github.ref_name }}
            ${{ vars.REPOSITORY_OWNER }}:${{ github.sha}}
            ghcr.io/${{ vars.REPOSITORY_OWNER }}:latest
            ghcr.io/${{ vars.REPOSITORY_OWNER }}:${{ github.ref_name }}
            ghcr.io/${{ vars.REPOSITORY_OWNER }}:${{ github.sha }}
