name: release-buildx

on:
  push:
    tags:
      - '*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,amd64
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Set Release Tag Env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - 
        name: docker hub login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      - 
        name: docker ghcr login
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            docker login ghcr.io -u $GITHUB_USER -p $GITHUB_TOKEN
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            $GITHUB_REPOSITORY:$GITHUB_SHA
            $GITHUB_REPOSITORY:$RELEASE_VERSION
            $GITHUB_REPOSITORY:latest
            ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
            ghcr.io/$GITHUB_REPOSITORY:$RELEASE_VERSION
            ghcr.io/$GITHUB_REPOSITORY:latest
